# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
    inputs: 
      tag:
        type: string
        required: true
        description: "release tag"
      commit:
        type: string
        required: false
        default: "main"
        description: "release commit"

jobs:

  build:

    permissions: write-all
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: ./barordo

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.1'

    - name: Build for Linux
      run: go build -o ../release/barordo -v
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Build for Windows
      run: go build -o ../release/barordo.exe -v
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Pack Barotrauma mod
      run: zip -r release/barordo-serverinfo.zip barordo-serverinfo
      working-directory: ./

    - name: Publish release
      uses: ncipollo/release-action@v1.21.0
      with:
        tag: ${{ inputs.tag }}
        commit: ${{ inputs.commit }}
        artifacts: "release/barordo,release/barordo.exe,release/barordo-serverinfo.zip"
        
        
    # - name: Test
    #   run: go test -v ./...
    
